# Generated by Django 4.1.7 on 2023-05-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=10)),
                ('conectividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.conectividadimpresora')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.marcaimpresora')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.modeloimpresora')),
            ],
        ),
    ]
