# Generated by Django 4.1.7 on 2023-05-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
        ('salida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.impresoras')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
